name: pixi_dart
dependencies:
  browser: any
transformers:
- $dart2js:
    $exclude: "lib/extras/ext_rope.dart"
    $exclude: "web/bin/*"
    $exclude: "web/examples/*"
    checked: true
    minify: false
    suppressWarnings: true
    suppressHints: false
    verbose: true
    terse: true
    analyzeAll: true
    $exclude: "bin/*"
    $exclude: "examples/*"