name: play_pixi
version: 0.10.5
author: playif <playif@gmail.com>
description: A Dart port for PIXI.js (v1.6.1) library.
homepage: https://github.com/playif/play_pixi
dev_dependencies:
  browser: any
  hop: any
  unittest: any
transformers:
- $dart2js:
    checked: true
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true