name: play_pixi
version: 0.10.2
description:
  A Dart port for PIXI.js (v1.6.1) library.
author: playif <playif@gmail.com>
homepage: https://github.com/playif/play_pixi
dependencies:
  browser: ">=0.10.0+2 <0.11.0"

dev_dependencies:
  hop: any
  unittest: any

transformers:
- $dart2js:
    checked: true
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    analyzeAll: false
