name: play_pixi
version: 0.9.0
description:
  A dart port for PIXI.js library.
author: playif <playif@gmail.com>
homepage: https://github.com/playif/pixi_dart
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
transformers:
- $dart2js:
    checked: true
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true