name: pixi_dart
suppressWarnings: false
dependencies:
  browser: any
transformers:
- $dart2js:
    checked: true
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true