name: pixi_dart
dependencies:
  browser: any
transformers:
- $dart2js:
    checked: true
    minify: false
    suppressWarnings: true
    suppressHints: false
    verbose: true
    terse: true
    analyzeAll: true